image: docker:28-cli

services:
  - docker:28-dind

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

stages:
  - build
  - deploy

build-and-publish:
  stage: build
  script:
    - echo "üîê Docker Login..."
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

    # Projektname in Kleinbuchstaben umwandeln
    - export LOWERCASE_PROJECT_PATH=$(echo "$CI_PROJECT_PATH" | tr '[:upper:]' '[:lower:]')
    - export DOCKER_IMAGE_NAME="$CI_REGISTRY/$LOWERCASE_PROJECT_PATH"
    - echo "üê≥ Baue Docker-Image - $DOCKER_IMAGE_NAME:$CI_COMMIT_TAG"

    - docker build -t "$DOCKER_IMAGE_NAME:$CI_COMMIT_TAG" .
    - docker tag "$DOCKER_IMAGE_NAME:$CI_COMMIT_TAG" "$DOCKER_IMAGE_NAME:latest"

    - echo "üì§ Push Images..."
    - docker push "$DOCKER_IMAGE_NAME:$CI_COMMIT_TAG"
    - docker push "$DOCKER_IMAGE_NAME:latest"
  only:
    - tags

notify-success:
  stage: deploy
  image: alpine:latest
  script:
    - echo "‚úÖ Database Backup Manager Docker Image $CI_COMMIT_TAG wurde erfolgreich ver√∂ffentlicht!"
  only:
    - tags
  needs:
    - build-and-publish
