# For local testing use host.docker.internal to connect to host machine databases
services:
  app:
    image: dbm
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:/app/db/prod.db
      - ENCRYPTION_KEY=8676644b7806852ee7ccb73b1f6b4771c59a5211ac45d52af8c5a60d9c616b57 # openssl rand -hex 32
      - BETTER_AUTH_URL=http://localhost:3000
      - BETTER_AUTH_SECRET=8hD99oq1xDqB8pX/Xz/d+NP+ASQMsuj2rcqtcUTktAk= # openssl rand -base64 32
      - TEST_DB_HOST=host.docker.internal
      # Add other env vars here
    volumes:
      # Persist backups
      - ./.test/backups:/backups
      # Persist SQLite DB in a dedicated folder
      - ./.test/db-data:/app/db
      # Persist Uploads/Avatars
      - ./.test/storage:/app/storage