services:
  app:
    image: registry.gitlab.com/skyfay/database-backup-manager:dev
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:/app/db/prod.db
      - ENCRYPTION_KEY= # openssl rand -hex 32
      - BETTER_AUTH_URL=http://localhost:3000
      - BETTER_AUTH_SECRET= # openssl rand -base64 32
      # Add other env vars here
    volumes:
      # Persist backups
      - ./backups:/backups
      # Persist SQLite DB in a dedicated folder
      - ./db-data:/app/db
      # Persist Uploads/Avatars
      - ./storage:/app/storage
